name: update-stats
concurrency: update-stats

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepo:
          - 'khulnasoft/*'
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run GH Repo Stats for Khulnasoft
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.ORG_REPO_TOKEN }}
          databranch: main

  update-stats-external:
    if: always()
    needs: update-stats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepoExt:
          - 'khulnasoft-lab/*'
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run GH Repo Stats for Khulnasoft Lab
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ matrix.statsRepoExt }}
          ghtoken: ${{ secrets.ORG_REPO_TOKEN }}
          databranch: main
